### PR TITLE
v2.1.17 Hop and skip a version - new Schedules enpoint/Hotfixes for the custom-line-pages endpoint

### LINKED ISSUE #158: v2.1.17 Testing
Based on testing for route 2 using this URL:

`https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA/route_stops_grouped/2`

## Issues

1. Duplicate times are showing up.  Based on looking at the results being returned, `departure_times` for all day types are being returned lumped together, instead of being separated out for each day type.

image

2. `departure_times` and `geojson` values are returning as strings.

image

3. Endpoint is returning an object inside an array. This makes sense if we're potentially returning multiple objects, but it doesn't make sense if we're only ever returning a single object.

image

## Checklist
- [x] Make sure the `departure_times` being returned are specific to that particular day type.
- [ ] Return values for `departure_times` and `geojson` as js objects instead of strings.
- [x] Return as an object instead of an array of objects.

### PR DESCRIPTION
**Pull request by albertkun**
This PR closes #158 #153

### Change log

Hotfixes to the `custom-line-pages` endpoint are included in this new version.

New endpoint added at `https://localhost/LACMTA/schedules/`, takes in, `list`, `all` or a specific `route_code`

- feat: [api] added `schedules` endpoint
- feat: model for schedules endpoint
- bump: version number
- feat: [api] added lat/lng for `route_stops` endpoints 
- fix: [api] incorrect multi-index for `route_stops` model
- fix: [api] `direction_id` included in returns
- fix: [api] all `custom-line-pages` endpoints good to go!

### Notes
`geojson` is still formatted as text though.

### CODE REVIEW

**Comment by matikin9** [comment]
@albertkun I'm looking at this endpoint:

https://api.metro.net/LACMTA_Rail/route_stops/801

* the JSON key names should be in quotes?  😢 I keep forgetting about this.
* all the objects in the array (except 1) are `day_type: "saturday"` and `direction_id: 1`.  For some reason, there is one object returned that is `day_type: "weekday"` and `direction_id: 0`.  No other stops are returned for `weekday`.  I'm checking the [timetable PDF](https://cdn.beta.metro.net/wp-content/uploads/2022/02/07163008/801_TT_09-06-22.pdf) and it looks like it runs the same schedule on Saturdays and Sundays.  Could that be killing the join if there is no Sunday?  The times themselves look correct in matching the times for the Southbound schedule.

**Comment by matikin9** [comment]
Ooops... I was on production earlier.  Testing on dev now and I'm seeing something completely different:

https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA_Rail/route_stops/801

image

https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA_Rail/route_stops_grouped/801

image

**Comment by matikin9** [comment]
Testing:
https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA_Rail/route_stops/801

I'm only getting 21 objects returned for `day_type: "saturday"` because they are all `direction_id: 1`.  I'm not seeing any `direction_id: 0` being returned for `day_type: "saturday"`.

For `day_type: "weekday"` it's the opposite.  I'm seeing 20 objects returned and they are all `direction_id: 0`, with no `direction_id: 1` results.

**Comment by albertkun** [comment]
these have all been addressed with the latest commit into dev #165 :) i also took out the `geojson` field from the `payload`.

**Comment by matikin9** [comment]
Departure times looking good now: 
image

**Comment by matikin9** [comment]
`https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA/route_stops/{route_code}`
and
`https://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA/route_stops_grouped/{route_code}`

look good ✔️

**Pull request merged**
